### ISSUE TITLE
Play Sports 1080p

### ISSUE THREAD

**Issue by Rphil29** [add-ons/plugin.video.yelo#7]
Hello, is it possible to broadcast the channels of Play Sports in 1080p instead of the current 720p? I know Telenet changed the stream quality of those channels from 720p to 1080p (on their website and app) so maybe this can be an update for the plugin?

**Comment by shycoderX** [comment]
This is due to the settings in InputStream Adaptive. For testing disable automatic stream selection in inputstream adaptive plugin settings. You should then be able to see the 1080p option. 

If you want to keep automatic stream selection and always pick the highest bitrate. You need to change the minimum bitrate value in there as well.

**Comment by piejanssens** [comment]
My settings for max resolutions including 1080p:

### Yelo add-on
- max bandwith 0

### Inputstream adaptive add-on

- min bandwidth 0
- max bandwidth 0
- stream selection: auto

I was going to question the value of having the bandwidth setting inside of Yelo itself, but I see it's going to be removed in 1.0. 👍

**Comment by dagwieers** [comment]
Being able to set the bandwidth inside Yelo is useful to be able to select the quality on a per-addon (per-source) basis.

If you only have one selection in Kodi, you cannot really set the quality, because the bandwidth/quality relation is different for different sources as it depends on the encoding.
